version: '3.5'

services:
  nginx:
    build: 前端/
    networks:
      - nginx-bridge
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-kaxabu.ithuan.tw}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:-kaxabu.ithuan.tw}
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always
  gunicorn:
    build: 後端/
    networks:
      - nginx-bridge
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-dbkaxabu.ithuan.tw}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:-dbkaxabu.ithuan.tw}
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always

networks:
  nginx-bridge:
    external: true
