version: '3.5'

services:
  nginx:
    build: 前端/
    networks:
      - nginx-bridge
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST_TSIANTUAN:-kaxabu.ithuan.tw}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_TSIANTUAN:-kaxabu.ithuan.tw}
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always
  gunicorn:
    build: 後端/
    networks:
      - nginx-bridge
      - default
    environment:
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      VIRTUAL_HOST: ${VIRTUAL_HOST_AUTUAN:-dbkaxabu.ithuan.tw}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_AUTUAN:-dbkaxabu.ithuan.tw}
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always
  postgres:
    image: postgres:15
    labels:
      - backup.postgres=true
    environment:
      POSTGRES_PASSWORD: ithuan
    volumes:
      - "postgres_database:/var/lib/postgresql/data"
    restart: always

volumes:
  postgres_database:

networks:
  nginx-bridge:
    external: true
